stages:
- build
- test
- sonarqube
- deploy

build:
 stage: build
 script:
 -  cd AmazonClone/Backend
 -  ./gradlew build -x test
 -  ./gradlew.bat --stop

test:
 stage: test
 script:
 -  cd AmazonClone/Backend
 -  ./gradlew test
 -  ./gradlew.bat --stop
 

sonarqube:
  stage: sonarqube
  allow_failure: true
  script:
    - cd AmazonClone/Backend
    - ./gradlew sonarqube 
    - ./gradlew.bat --stop

deploy:
  stage: deploy
  allow_failure: true
  script:
    - cd AmazonClone/
    - docker-compose down
    - docker-compose build
    - docker container ls -a


